[package]
name = "vmb-proto"
version = "0.1.0"
authors = ["Henrik Boeving <boeving@hm.edu>"]
edition = "2018"


[dependencies]
tokio-util = { version =  "0.4.0", features = ["codec"]}
bytes = "0.5.0"
byteorder = "1.3.4"
